# Generated by Django 4.1.2 on 2022-10-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("puppy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuppyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Puppy status",
            },
        ),
        migrations.AddField(
            model_name="puppy",
            name="status",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="puppy",
                to="puppy.puppystatus",
            ),
            preserve_default=False,
        ),
    ]
