# Generated by Django 4.1.2 on 2022-10-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("puppy", "0003_puppybreed_puppy_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuppyColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="puppy",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="puppy.puppycolor",
            ),
        ),
        migrations.AddField(
            model_name="puppybreed",
            name="color",
            field=models.ManyToManyField(related_name="breed", to="puppy.puppycolor"),
        ),
    ]
