# Generated by Django 4.1.2 on 2022-10-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0005_parentkennel"),
        ("puppy", "0005_puppygender_puppy_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuppyBrood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "bitch",
                    models.ForeignKey(
                        limit_choices_to={"gender": 2},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitch",
                        to="parents.parent",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        limit_choices_to={"gender": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sire",
                        to="parents.parent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="puppy",
            name="brood",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puppy",
                to="puppy.puppybrood",
            ),
        ),
    ]
