# Generated by Django 4.1.2 on 2022-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("birth", models.DateTimeField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
