# Generated by Django 4.1.2 on 2022-10-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0002_parentbreed_parent_breed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentGender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=6)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="parent",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parent",
                to="parents.parentgender",
            ),
        ),
    ]
