# Generated by Django 4.1.2 on 2022-10-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0004_parentcolor_parent_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentKennel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kennel",
                        to="parents.parent",
                    ),
                ),
            ],
        ),
    ]
